### ISSUE TITLE
Group Contract

### ISSUE THREAD

**Issue by TimothyZG** [DSCI-310/DSCI-310-Group-1#1]
Finish and submit the group project

**Comment by danielhou13** [comment]
Remember to add your availability to the contract.

Heres the milestone deadlines according to the syllabus:
2022/02/19 Milestone 1
2022/03/12 Milestone 2
2022/03/26 Milestone 3
2022/04/09 Final Project due

**Comment by TimothyZG** [comment]
Here's the link to the group contract: https://docs.google.com/document/d/111JTniIblfbpQX8s0Xxq1ukXnhhPKvcv2de0emnPRM4/edit
