### ISSUE TITLE
Which license to keep

### ISSUE THREAD

**Issue by gzzen** [DSCI-310/DSCI-310-Group-1#13]
There are now two licenses, CA BY-SA 4.0 and MIT being quoted at the README page. I think we only need to keep one. The license file in our repository only mentioned the first one, so should we just discard the sentence for MIT license?

**Comment by danielhou13** [comment]
It says we need two licenses on the milestones

**Comment by danielhou13** [comment]
License’s tell others how they may (or may not) use your work. We will learn more about licenses later in the course, and for now **we recommend using an [MIT license](https://opensource.org/licenses/MIT)** for the project code and a **Creative Commons [Attribution-NonCommercial-NoDerivatives 4.0 International (CC BY-NC-ND 4.0)](https://creativecommons.org/licenses/by-nc-nd/4.0/) license for the project report**. As long as your group agrees, these can be changed later in the course when you learn more about licenses. If you want to spend some time choosing different licenses now, we can recommend these two websites to help get you started:

**Comment by gzzen** [comment]
> License’s tell others how they may (or may not) use your work. We will learn more about licenses later in the course, and for now **we recommend using an [MIT license](https://opensource.org/licenses/MIT)** for the project code and a **Creative Commons [Attribution-NonCommercial-NoDerivatives 4.0 International (CC BY-NC-ND 4.0)](https://creativecommons.org/licenses/by-nc-nd/4.0/) license for the project report**. As long as your group agrees, these can be changed later in the course when you learn more about licenses. If you want to spend some time choosing different licenses now, we can recommend these two websites to help get you started:

Got it, thanks!
