### ISSUE TITLE
Use Jupyter Book to reformat analysis 

### ISSUE THREAD

**Issue by danielhou13** [DSCI-310/DSCI-310-Group-1#32]
Last thing to do for this milestone

**Comment by gzzen** [comment]
`make` not working after `jupyter-book build analysis/`. Need to seek for some help

**Comment by gzzen** [comment]
> `make` not working after `jupyter-book build analysis/`. Need to seek for some help

But it works fine for `build` after `make`. So it should not be a big problem generating the report. However running for the second time may fail...

**Comment by danielhou13** [comment]
Did you do make or make all

**Comment by danielhou13** [comment]
The problem I can think of off the top of my head is that maybe the order that you call build and the rest of the scripts in the makefile isn't correct right now

**Comment by gzzen** [comment]
Thanks, I'll try that

**Comment by gzzen** [comment]
It works after `make clean`. Problem solved.
