### ISSUE TITLE
Create the analysis using the student performance dataset

### ISSUE THREAD

**Issue by danielhou13** [DSCI-310/DSCI-310-Group-1#6]
Dataset: https://archive-beta.ics.uci.edu/ml/datasets/student+performance

I was thinking we just pick a few of the features to predict final grade. Some features I think are interesting include Pstatus, study time, free time, Parent education, Parent Jobs, and time spent with friends. What other features seem interesting?

**Comment by gzzen** [comment]
As the professor mentioned before, we are not expected to use any knowledge further than DSCI 100. If we were to predict the numeric final grade using the given inputs, multiple regression is possibly needed. Not sure if that would be an issue.

**Comment by danielhou13** [comment]
Should be fine. Multivariable regession is functionally the same as doing linear regression so that shouldnt be problematic. Picking what features to use would be a more pressing issue.

**Comment by gzzen** [comment]
I'm perfectly okay with the variables you mentioned (Pstatus, study time, free time, Parent education, Parent Jobs, and time spent with friends). And there are many relative research for support, could be some good references.

**Comment by gzzen** [comment]
> Should be fine. Multivariable regession is functionally the same as doing linear regression so that shouldnt be problematic. Picking what features to use would be a more pressing issue.

Just talked with our TA, multiple linear regression or even more advanced methods are allowed, as long as they are well-explained.
